import type { Metadata } from 'next'
import { Geist, Geist_Mono, Inter, Raleway, Roboto } from 'next/font/google'

import { Providers } from '@/providers/Providers'

import { SITE_NAME } from '@/constants/constants'

import './globals.css'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
	title: {
		absolute: `${SITE_NAME}`,
		template: `${SITE_NAME} | %s`
	},
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			className={roboto.variable}
		>
			<body className={`${roboto.className} antialiased`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
